[package]
name = "noitarchiver_cmd"
version = "3.0.0"
authors = ["Xiaomony"]
edition = "2021"
build = "build.rs"


[dependencies]
colored = "2.1.0"
noitarchiver_core = { path="../Core" }

[build-dependencies]
winres = "0.1.12"