[package]
name = "noitarchiver_core"
version = "3.2.0"
authors = ["Xiaomony"]
edition = "2021"


[dependencies]
chrono = "0.4.38"
dirs = "5.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.117"
